Scrollable-div, Form check - #157
InfTkm/anything-nft pull request #219
Opened 2022-07-06 02:49 UTC by WilliamJiH

Added scrollable-div, checkbox for terms and conditions, and simple css.
Added notification for empty first name and checkbox, last 3s. If both selected, then proceed.

2022-07-07 02:46 UTC, yuliwilliam approved these changes

2022-07-07 02:47 UTC, yuliwilliam requested changes
should be good to go as soon as u update with the real terms and conditions

2022-09-22 04:50 UTC, InfTkm approved these changes
well done

2022-09-22 04:52 UTC, yuliwilliam approved these changes

2022-09-22 12:55 UTC, merged